### ISSUE TITLE
not able handle touch on child cells

### ISSUE THREAD

**Issue by rajputvishal** [jeantimex/ios-swift-collapsible-table-section#10]
when I click on the header the handler for "cellForRowAt" gets called but no handler is there for click on the child

**Comment by jeantimex** [comment]
Hi @rajputvishal, I guess you need to add `didSelectRowAtIndexPath` in the controller:

```
override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
  // perform cell click handler here...        
}
```

The `cellForRowAt` is telling the table view controller how to render each row, when we collapse or expand the section, we update the height for each row, at that point, we ask the renderer to redraw, and the `cellForRowAt` will be triggered.
