### ISSUE TITLE
Add image to UITableViewHeaderFooterView

### ISSUE THREAD

**Issue by Jack0805** [jeantimex/ios-swift-collapsible-table-section#11]
Hi, how can I add a image to the UITableViewHeaderFooterView? Just a small  square image on the most left hand side of the section. What I tried so far is, in CollapsibleTableViewHeader controller:

let titleimage = UIImageView()
contentView.addSubview(titleimage)

then, in struct Section, add another var images: UIImage! and init it.

I also put it into the section array like this:

Section(name: "Mac", images: UIImage(named: "com-taou-avatar.png")!, items: ["MacBook", "MacBook Air", "MacBook Pro", "iMac", "Mac Pro", "Mac mini", "Accessories", "OS X El Capitan"]),

Finally, set up it in viewForHeaderInSection below:
    // Header
    override func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
       ......
        header.titleimage.image = sections[section].images
        return header
    }

However, still no image appears on the section bar...can you help?

Thanks!!

**Comment by L4grange** [comment]
I just implemented it for my own project, you need to modify the CollapsibleTableViewHeader Class to add an imageView as well as some constrains to keep it in place. See my class below and compare it to the original, you can clearly see the "imageView" code:

`
//
//  CollapsibleTableViewHeader.swift
//  ios-swift-collapsible-table-section
//
//  Created by Yong Su on 5/30/16.
//  Copyright © 2016 Yong Su. All rights reserved.
//

import UIKit

protocol CollapsibleTableViewHeaderDelegate {
    func toggleSection(_ header: CollapsibleTableViewHeader, section: Int)
}

class CollapsibleTableViewHeader: UITableViewHeaderFooterView {
    
    var delegate: CollapsibleTableViewHeaderDelegate?
    var section: Int = 0
	
	let imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: 30, height: 30))
    let titleLabel = UILabel()
    let arrowLabel = UILabel()
    
    override init(reuseIdentifier: String?) {
        super.init(reuseIdentifier: reuseIdentifier)
        
        //
        // Constraint the size of arrow label for auto layout
        //
		/*
		if #available(iOS 9.0, *) {
			arrowLabel.widthAnchor.constraint(equalToConstant: 12).isActive = true
			arrowLabel.heightAnchor.constraint(equalToConstant: 12).isActive = true
		} else {
			// Fallback on earlier versions
			//TODO: - Find a fix for iOS 8. I need to implement the constraints manually.
			//For now it seems to be working even without the constraints
		}
		*/
		
		imageView.translatesAutoresizingMaskIntoConstraints = false
        titleLabel.translatesAutoresizingMaskIntoConstraints = false
        arrowLabel.translatesAutoresizingMaskIntoConstraints = false
		
		contentView.addSubview(imageView)
        contentView.addSubview(titleLabel)
        contentView.addSubview(arrowLabel)
        
        //
        // Call tapHeader when tapping on this header
        //
        addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(CollapsibleTableViewHeader.tapHeader(_:))))
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        
        contentView.backgroundColor = UIColor(hex: 0x2E3944)
		
		imageView.contentMode = .scaleAspectFit
        titleLabel.textColor = UIColor.white
        arrowLabel.textColor = UIColor.white
		
        //
        // Autolayout the lables
        //
        let views = [
			"imageView" : imageView,
            "titleLabel" : titleLabel,
            "arrowLabel" : arrowLabel,
        ]
		
		contentView.addConstraints(NSLayoutConstraint.constraints(
			withVisualFormat: "H:|-20-[imageView(==30)]-[titleLabel]-[arrowLabel]-20-|",
			options: [],
			metrics: nil,
			views: views
		))
		
		contentView.addConstraints(NSLayoutConstraint.constraints(
			withVisualFormat: "V:|-[imageView]-|",
			options: [],
			metrics: nil,
			views: views
		))
		
		contentView.addConstraints(NSLayoutConstraint.constraints(
			withVisualFormat: "V:|-[titleLabel]-|",
			options: [],
			metrics: nil,
			views: views
		))
		
		contentView.addConstraints(NSLayoutConstraint.constraints(
			withVisualFormat: "V:|-[arrowLabel]-|",
			options: [],
			metrics: nil,
			views: views
		))
    }
    
    //
    // Trigger toggle section when tapping on the header
    //
    func tapHeader(_ gestureRecognizer: UITapGestureRecognizer) {
        guard let cell = gestureRecognizer.view as? CollapsibleTableViewHeader else {
            return
        }
        
        delegate?.toggleSection(self, section: cell.section)
    }
    
    func setCollapsed(_ collapsed: Bool) {
        //
        // Animate the arrow rotation (see Extensions.swf)
        //
        arrowLabel.rotate(collapsed ? 0.0 : CGFloat(Double.pi / 2))
    }
    
}
`

Also, you need to add an Image to the Section struct (which you did) and then set the image in 
`override func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {`
using 
`header.imageView.image = sections[section].image`

Enjoy!

**Comment by jeantimex** [comment]
Thanks @L4grange! I just migrated the project to Swift 3, I know it's been too long, been working on other React related projects.

This project is mainly for demonstrating how to implement collapsible sections, customizing `UITableViewHeaderFooterView` is out of scope, but I like your solution, hope that helps @Jack0805 . :)

**Comment by L4grange** [comment]
Yup! Using it in my project with some customizations as my SideMenu and your code helped me greatly!
