### ISSUE TITLE
want to add labels and buttons as an items 

### ISSUE THREAD

**Issue by BugFinder27** [jeantimex/ios-swift-collapsible-table-section#16]
![screen shot 2017-05-30 at 3 53 59 pm](https://cloud.githubusercontent.com/assets/28896246/26579165/4a049976-4550-11e7-82b1-5b56ecf41cf3.png)
what should i do if i want to place labels and buttons in place of product names and at the same data is coming from the server. hoping for the reply. thank you so much in advance

**Comment by jeantimex** [comment]
Hi @BugFinder27, in that case, you have to implement a custom table cell, and you have to take auto layout into consideration, I would recommend this library for doing the auto layout for you: SnapKit and Cartography, they all support Swift 3 very nicely.
