### ISSUE TITLE
auto layout issue if you change the row height

### ISSUE THREAD

**Issue by juyoung1991** [jeantimex/ios-swift-collapsible-table-section#18]
Great job with this collapsible!

I implemented a tableview inside the collapsible so each collapsible header will open up a tableview.

To do this, i had to increase the height of the row from 44 to 400 since 44 was wayy to short and i could only see a glimpse of my tableview.

I get a 

 " [LayoutConstraints] Unable to simultaneously satisfy constraints. "

error.

I came to conclusion that when you expand one of your collapisble and if at least one 'other' collapsible header goes out of the view because the expanded row was too tall, it will throw this error.

I've been really trying to figure this out but had no luck.

**Comment by jeantimex** [comment]
Hi @juyoung1991, I guess the solution to make the cell support dynamic height or auto height. I am working on the feature at the moment, will share you with what I come up later on. Thanks for your support.

**Comment by LukA888** [comment]
Any update for this? 😄

PD: Thanks for the library!

**Comment by jeantimex** [comment]
I am working on this feature on this branch: https://github.com/jeantimex/ios-swift-collapsible-table-section/pull/22

Right now, there is a bug that the cell height is not consistent after being collapsed, let me know if you guys want to help me on that. :)

**Comment by jeantimex** [comment]
Hey guys, it's merged to the master branch, enjoy auto sizing and collapsing!
