### ISSUE TITLE
Problem with image cell

### ISSUE THREAD

**Issue by orazz** [jeantimex/ios-swift-collapsible-table-section#19]
![simulator screen shot jun 22 2017 1 32 34 pm](https://user-images.githubusercontent.com/8214953/27424682-576621dc-574f-11e7-96ee-c81f28fd59f4.png)

**Comment by jeantimex** [comment]
Hi @orazz, I just implemented the autosizing feature, please take a look and you might have to make sure the content (e.g. the image) can stretch properly to the top and bottom of the cell. You can take a look at the latest example, it has a custom cell that supports autolayout and autosizing.
