### ISSUE TITLE
about the collapsible table section

### ISSUE THREAD

**Issue by ledikari** [jeantimex/ios-swift-collapsible-table-section#2]
hello, Im a newbie in swift and I find your project very cool and useful. I tried using your project but i add section into another group (add sections on manufacture group). In addition,  Can you also show examples on how to alter/custom the group cell?

thanks 
Led.

**Comment by jeantimex** [comment]
Hi @ledikari, thanks a lot! Do you mean having grouped-style sections? If so, please take a look at my other example which will show you how to achieve what you want. 

https://github.com/jeantimex/ios-swift-collapsible-table-section-in-grouped-section

Let me know if you have any questions :)

**Comment by jeantimex** [comment]
Hi @ledikari, I am closing this issue, let me know if you still have any question. :)
