### ISSUE TITLE
How best to Expand only one section?

### ISSUE THREAD

**Issue by daviddelmonte** [jeantimex/ios-swift-collapsible-table-section#21]
Would it be possible to have an option to only expand one section at a time? So, when one section expands, all other sections close. How to best implement this? Thanks

**Comment by jeantimex** [comment]
Hi @daviddelmonte, we had a discussion in this thread: https://github.com/jeantimex/ios-swift-collapsible-table-section/issues/20, let me know if that makes sense to you. :)
