### ISSUE TITLE
compile error!!!!

### ISSUE THREAD

**Issue by ttoggaiman** [jeantimex/ios-swift-collapsible-table-section#3]
my env : xcode8, swift 2.3 (use lagacy swift check) 
i have download source file and open and build..
i got error below 
what can i do??

![cap2](https://cloud.githubusercontent.com/assets/22382653/18823322/ccb9c52c-83f3-11e6-92d3-93ca0463a31e.png)

**Comment by jeantimex** [comment]
Thanks @ttoggaiman, I am working on a separate branch to tackle this issue, in the meantime I am going to ditch the storyboard.

**Comment by jeantimex** [comment]
Hi @ttoggaiman, I've fixed this issue in swift-2.3 branch and merged to master.
