### ISSUE TITLE
Swift 3 & Pods

### ISSUE THREAD

**Issue by mayooresan** [jeantimex/ios-swift-collapsible-table-section#7]
Could you please merge the swift 3 branch into main branch as Swift 3 is mainstream right now. Also would you mind adding pods support please?

**Comment by jeantimex** [comment]
Hi @mayooresan, totally agree, will try to merge the swift 3 (need to update the readme for it). For the pod, I am thinking what interfaces to provide, but will certainly work on that soon.

**Comment by swervdev01** [comment]
hey @jeantimex ,
Any chance you will be migrating this project in the near future?

**Comment by samirthebti** [comment]
Any Update ?

**Comment by jeantimex** [comment]
I have migrated to Swift 3 in master branch, going to update the readme soon.

**Comment by jeantimex** [comment]
Just implemented the autosizing feature, finally it's time to start the pod implementation. I will keep you guys updated.

To be honest, this will be my first pod, please give me some time. Also if you guys want to contribute, let me know. :)

**Comment by jeantimex** [comment]
I am starting the pod project here: https://github.com/jeantimex/CollapsibleTableSectionViewController, let me know if you want to contribute. Close this ticket because Swift 3 is fully supported now and the Pod project is going on.
