### ISSUE TITLE
Headers Separator lines overlaps while scrolling

### ISSUE THREAD

**Issue by mohammadghk** [jeantimex/ios-swift-collapsible-table-section#8]
Hi
when I expand headers and scroll the `UITableview` up and down fast some lines appears inside some of my cells. (separator lines between sections)
any Idea on how can It be fixed?

**Comment by mohammadghk** [comment]
I finally solved the issue by setting `heightForFooterInSection` to `0.0` 😄

**Comment by WalidDev1** [comment]
tks mean for this resolve , you realy help me 💯
