### ISSUE TITLE
collapsible-table-section with storyboard

### ISSUE THREAD

**Issue by athzuma** [jeantimex/ios-swift-collapsible-table-section#9]
Hello, first I would like to congratulate the good work!
Now to my question, I'm implementing it for storyboard, and some doubts are emerging. and I wonder if there is any example of using implemented via storyboard?

**Comment by jeantimex** [comment]
Hi @athzuma, yep, please check out Release v1.0, I was using storyboard before, checkout the readme in v1.0 and you will see the instructions there.

**Comment by athzuma** [comment]
thank you!
